export const ADD_STRATEGY = 'ADD_STRATEGY';
export const DELETE_STRATEGY = 'DELETE_STRATEGY';
export const EDIT_STRATEGY = 'EDIT_STRATEGY';
export const ADD_CONDITION = 'ADD_CONDITION';
export const DELETE_CONDITION = 'DELETE_CONDITION';
export const EDIT_CONDITION = 'EDIT_CONDITION';
